apiVersion: v1
kind: Service
metadata:
  name: simple-app-for-kube-service
  labels:
    app: simple-app-for-kube
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
  selector:
    app: simple-app-for-kube
  type: NodePort