apiVersion: v1
kind: Service
metadata:
  name: SIMPLE-APP-FOR-KUBE-SERVICE
  labels:
    app: simple-app-for-kube
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: simple-app-for-kube
  type: NodePort