logging:
  level:
    org.springframework.*: DEBUG
    reactor.netty.http.client: DEBUG
    root: DEBUG
 

server:
   port: 1010 
   

spring:
   application:
      name: GATEWAY-SERVICE



   
          